package ru.vsu.cs.picstorm.entity;

public enum RoleAuthority {
    UPLOAD_AUTHORITY,
    SUBSCRIBE_AUTHORITY,
    REACT_AUTHORITY,
    BAN_PUBLICATION_AUTHORITY,
    BAN_USER_AUTHORITY,
    MANAGE_ADMINS_AUTHORITY
}
